### ISSUE TITLE
Package categories doesn't make any sense

### ISSUE THREAD

**Issue by zdenekpetrzd** [Zdendaki/RailworksDownloader#13]
**Describe the bug**
Package categories in the app are completely different from the ones on server and often make zero sense.

**To Reproduce**
Open the app.
Have some packages installed.
Compare package categories in the app with the ones on server.

**Expected behavior**
Loco 754 dependencies are not showing up as scenery  and locomotives are not showing up as wagons.

**Screenshots**
![image](https://user-images.githubusercontent.com/42700180/104107978-2520bb80-52c1-11eb-9876-35f61d73dfe3.png)

**Please complete the following information:**
Version [e.g. 0.9.3.2]

**Comment by JachyHm** [comment]
Resolved in ef8cfaf by localisations.
