### ISSUE TITLE
Corrupting SERZ file custom encoded characters

### ISSUE THREAD

**Issue by Luki156** [Zdendaki/RailworksDownloader#14]
Kódování v xml a bin souborech by mělo být ve formátu UTF-8. Při použití na DE nebo AU tratích se objevují znaky jako "äöü", které jsou převedeny na UTF-8. Aplikace DLS Client je při detekci na chybějící věci převede na UTF-16. Takže např. hlásí že chybí: 
ve složce 1216_ÖAMTC\OEBB_1216_1xx_.bin
Formát v RW Tools je: <BlueprintID d:type="cDeltaString">Electric\1216_1xx\1216_ďż–AMTC\OEBB_1216_1xx_.xml</BlueprintID>
DLS Client je: "Electric\1216_1xx\1216_ￖAMTC\OEBB_1216_1xx_.xml"
Takže pak hlásí, že chybí, ale ve skutečnosti tam je.

Předpokládám že by v Utils.cs měla být proměnná path_component deklarována jako "byte" aby mohl být proveden konvert na UTF-8 systémově. Něco jsem zkoušel, ale C# tak dobře neznám.
Luky

**Comment by JachyHm** [comment]
Problém je každopádně trochu složitější, rozhodně bude potřeba upravit SerzReader.cs a ne Utils.cs, každopádně způsob kódování v TS zdá se mi poněkud podivný.
Ještě se tomu budu věnovat.
Prozatím příprava v c1349b4b.
