### ISSUE TITLE
Application failing when reading corrupted RouteProperties.xml

### ISSUE THREAD

**Issue by sasule** [Zdendaki/RailworksDownloader#16]
**Describe the bug**
Application was failing to show list of routes when there was a corrupted RouteProperties.xml file. Hotfixed by [this pull request](https://github.com/Zdendaki/RailworksDownloader/pull/15)

**To Reproduce**
1. Download and install Altenburg - Wildau route (7ecaf8d4-8aa0-4a42-8c15-cd1af0f69bb7)
2. Start the app
3. See error (Version 0.9.3.2 fails, hotfixed version shows an error dialog shows and the continues) (slightly edited)

**Expected behavior**
Well, this is to be discussed. In my opinion if there is corrupted or not-well formed xml file the app should inform the user that RouteProperties.xml is unreadable for it. I do not know if there is any way how to try to fix some giberish in xml file (never searched for).
I think the user **should** be informed and the appliacation **may** try to read the file to get desired informations from it.

**Please complete the following information:**
OS:  Windows 10 (does not play any role)
Version: [0.9.3.2](https://github.com/Zdendaki/RailworksDownloader/tree/0.9.3.2)

**Additional context**
I've investigated a little bit: In this special case for Altenburg-Wildau Route (which does not affect the fact xml file is wrong) RouteProperties.xml is NOT xml at all but is "serz"-ed xml - Is's a .bin file just renamend to xml.
So there could be a chance to try to read the file if it is un-serz-ed. One can detect serz-ed file by its header - starts with "SERZ" string.

Attached file had to be renamed because the "xml" suffix is not accepted.
[RouteProperties.txt](https://github.com/Zdendaki/RailworksDownloader/files/5980198/RouteProperties.txt)

**Comment by JachyHm** [comment]
Honestly until now I had no clue that RouteProperties could possibly be SERZ file, what more with .xml extension.
Maybe best solution would be to create custom parser as we only need route name from the RP.
Anyways this should be probably solved together with #14 as I think some routes may have used this characters.

I will try implementing reading SERZ RouteProperties ASAP.

**Comment by JachyHm** [comment]
As of last update DLS ignores file extensions and explicitly searches files for both SERZ and XML file format.
Should resolve even situations like this one, where *.xml file is actually SERZ file.
