### ISSUE TITLE
Meaningful error messages

### ISSUE THREAD

**Issue by sasule** [Zdendaki/RailworksDownloader#17]
**Is your feature request related to a problem? Please describe.**
When some submodule of application throw an exception then an exception trace is shown. This sadly says nothing to the user (BFUs espescially) and the end user is really confused of what happend.

**Describe the solution you'd like**
Create a set of error messages that explain to user what happend. 
Eg. "The file could not be read because is corrupted" or "Connection to server could not be established".
Some log me be created for developers.

**Comment by JachyHm** [comment]
Resolved in ef8cfaf by creating localized messages and moving stack trace into "detailed part" of error window.
