### ISSUE TITLE
Automatically rescans when download cancelled

### ISSUE THREAD

**Issue by Lus0rius** [Zdendaki/RailworksDownloader#29]
**Describe the bug**
The software rescans assets every time a download is cancelled, even if this was the first download to happen.

**To Reproduce**
1. Click on a route with downloadable assets
2. Click on 'Download packages'
3. Click on 'Cancel'
4. Rescan happens

**Expected behavior**
If this was the first download and it has been cancelled by user : never rescan.
Else, let the user have the choice to rescan or not (maybe through a setting "Automatically rescan : Yes or No").

It would also be nice, since the rescan takes some time, if it didn't prevent the user to start downloading packages meanwile.

OS: Windows 10
Version 1.2.1.1

**Comment by JachyHm** [comment]
Most probably resolvced somewhere in process.
If not, please reopen the issue.
