### ISSUE TITLE
Download při prvním startu

### ISSUE THREAD

**Issue by silverarrow12** [Zdendaki/RailworksDownloader#3]
**Describe the bug**
Po dokončení stahování chybějících assetů přes "download missing assets" se aplikace **znova** zeptá, jestli nechci stáhnout znovu ty chybějící assety, které jsem stáhl přes "download missing assets"

**To Reproduce**
Po prvním scanu kliknout na tlačítko download missing assets, počkat až se dostáhne a mělo by vyskočit okno jestli nechci stáhnout znovu assety které mi "prý" chybí.

**Expected behavior**
Očekával jsem, že to po mně nebude chtít znovu download.

**Screenshots**
Nestihl jsem pořídit.

**Please complete the following information:**
OS: Windows 10
Version v0.1.12.2

**Additional context**
Nemám nic co bych dodal.

**Comment by Zdendaki** [comment]
Verze 0.1.12.2 není veřejnou testovací verzí. Zkus to zreprodukovat na poslední verzi.

**Comment by JachyHm** [comment]
Verze 0.1.12.2 je veřejnou DEBUG verzí.

**Comment by JachyHm** [comment]
Vyřešeno reloadem databáze v na začátku každého GetDownloadableDependencies v f06c6d44808952e23af916ab51f5f6ee2c501163.
