### ISSUE TITLE
Search bar not working

### ISSUE THREAD

**Issue by em1tter** [Zdendaki/RailworksDownloader#33]
Hi.
I was trying to search for something on the web [https://dls.rw.jachyhm.cz/](url) and whenever I tried to type something and search for it, then everything got just reloaded and it did not search for anything at all.
Thanks.

(Also thank you for this program, it is very useful:))

**Comment by em1tter** [comment]
I found the solution. You just have to not press enter after typing it:D

**Comment by Zdendaki** [comment]
Smart xd
