### ISSUE TITLE
Zamrznutí aplikace

### ISSUE THREAD

**Issue by zdenekpetrzd** [Zdendaki/RailworksDownloader#4]
**Describe the bug**
Aplikace zamrzne po kliknutí na další tlačítko pokud je již zahájen proces vytvářející dialogové okno.

**To Reproduce**
Kliknout na Download missing assets.
Kliknout na Rescan assets ještě předtím, než se objeví dialogové okno o stahování assetu.

**Expected behavior**
Nelze kliknout na další tlačítko, pokud je již zahájen proces zahájený kliknutím na předchozí tlačítko

**Please complete the following information:**
OS: Windows 10
Version 0.9.1.0

**Comment by JachyHm** [comment]
Vyřešeno zablokováním konfliktních tlačítek v f06c6d44808952e23af916ab51f5f6ee2c501163.
