### ISSUE TITLE
Override all / keep all local when asking for conflict packages

### ISSUE THREAD

**Issue by JachyHm** [Zdendaki/RailworksDownloader#5]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to manually click a LOT times on "Yes override this with DLS package" even when I want to override / keep local all.

**Describe the solution you'd like**
Add buttons "Override all" and "Keep all" when asking for conflict packages found.

**Comment by Zdendaki** [comment]
Added in release [0.9.3.0](https://github.com/Zdendaki/RailworksDownloader/releases/tag/0.9.3.0).
