### ISSUE TITLE
[BUG] Cannot download more missing packages

### ISSUE THREAD

**Issue by Zdendaki** [Zdendaki/RailworksDownloader#6]
**Describe the bug**
When I have already downloaded some assets and new appear, I cannot download them, because after clicking on "Download missing" will nothing happen.

**To Reproduce**
1. Have some packages installed
2. New missing packages will appear on website
3. I try to download them
4. Click on "Download button"

**Expected behavior**
Download dialog will appear and assets will download

**Please complete the following information:**
OS: Windows 10
Version 0.9.2.3

**Comment by JachyHm** [comment]
What exactly means "new appear"?
What exactly means "nothing happens"?
Do you download your "new missing packages" through button on site?

**Comment by Zdendaki** [comment]
Ad. 1: Someone adds new packages that I don't have
Ad. 2: After clicking on Download missing packages just nothing happens.
Ad. 3: I download missing packages through button in application.

**Comment by Zdendaki** [comment]
Ok, I found the problem. Packages will actually start downloading, but before download dialog appear, you have to wait approx. 30 seconds. So maybe I add a dialog to solve this confusion.
